BurgerMenuProject/Entities/Subscription.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Web;

namespace BurgerMenuProject.Entities
{
	public class Subscription
	{
        public int Id { get; set; }
        public string EmailAddress { get; set; }
        public DateTime dateTime { get; set; } = DateTime.Now;
    }
}

BurgerMenuProject/Areas/Admin/Controllers/SubscriptionController.cs
using BurgerMenuProject.Context;
using System;
using System.Collections.Generic;
using System.Linq;
using System.Web;
using System.Web.Mvc;
using PagedList;
namespace BurgerMenuProject.Areas.Admin.Controllers
{
    public class SubscriptionController : Controller
    {
        // GET: Admin/Subscription
        BurgerMenuContext context = new BurgerMenuContext();
        public ActionResult Index(int page = 1)
        {
            int pagesize = 10;
            var values = context.Subscriptions
                .OrderByDescending(s => s.Id)
                .ToList()
                .ToPagedList(page, pagesize);
			ViewBag.TotalPages = values.PageCount;
			ViewBag.CurrentPage = page;
			return View(values);
        }
    }
}

BurgerMenuProject/Areas/Admin/Views/Subscription/Index.cshtml
@model  PagedList.IPagedList<BurgerMenuProject.Entities.Subscription>
@{
    ViewBag.Title = "Index";
    Layout = "~/Areas/Admin/Views/AdminLayout/Index.cshtml";
}

<div class="col-lg-12 grid-margin stretch-card">
    <div class="card">
        <div class="card-body">
            <h4 class="card-title">Aboneler</h4>
            <p class="card-description">
            </p>
            <div class="table-responsive">
                <table class="table">
                    <thead>
                        <tr>
                            <th>E-Posta Adresi</th>
                            <th>Abonelik Tarihi</th>
                        </tr>
                    </thead>
                    <tbody>
                        @foreach (var item in Model)
                        {

                            <tr>
                                <td class="email">@item.EmailAddress</td>
                                <td>@item.dateTime.ToString("dd.MM.yyyy")</td>

                            </tr>
                        }
                    </tbody>
                </table>
            </div>
        </div>
    </div>

</div>
<button onclick="copyEmails()" class="btn btn-info col-lg-12" style="height:50px">E-Postaları Kopyala</button>

<script>
    function copyEmails() {
        const emails = Array.from(document.querySelectorAll('.email')).map(cell => cell.innerText);
        const emailList = emails.join(', ');
        navigator.clipboard.writeText(emailList).then(() => {
            alert('E-posta adresleri panoya kopyalandı!');
        }).catch(err => {
            console.error('Kopyalama hatası:', err);
        });
    }
</script>
<style>
    .pagination .page-item.active .page-link {
        background-color: #ec37fc; 
        border-color: #ec37fc;
        color: white;
    }

    .pagination .page-link {
        color: black;
    }

        .pagination .page-link:hover {
            color: #ec37fc; 
        }
</style>

<div class="row bt mt-4">
    <div class="col-sm-12 text-center">
        <ul class="pagination pagination-lg justify-content-center">
            @if (ViewBag.CurrentPage > 1)
            {
                <li class="page-item">
                    <a class="page-link" href="@Url.Action("Index", "Subscription", new { page = ViewBag.CurrentPage - 1 })" aria-label="Önceki">
                        <span aria-hidden="true">&laquo;</span>
                    </a>
                </li>
            }

            @for (int i = 1; i <= ViewBag.TotalPages; i++)
            {
                <li class="page-item @(i == ViewBag.CurrentPage ? "active" : "")">
                    <a class="page-link" href="@Url.Action("Index", "Subscription", new { page = i })">@i</a>
                </li>
            }

            @if (ViewBag.CurrentPage < ViewBag.TotalPages)
            {
                <li class="page-item">
                    <a class="page-link" href="@Url.Action("Index", "Subscription", new { page = ViewBag.CurrentPage + 1 })" aria-label="Sonraki">
                        <span aria-hidden="true">&raquo;</span>
                    </a>
                </li>
            }
        </ul>
    </div>
</div>